package at.fhv.lab1.eventbus.events;

public enum EventType {
    BOOK_ROOM,
    MASTERDATA_ROOM_INITIALIZED,
    MASTERDATA_CUSTOMER_INITIALIZED,
    MASTERDATA_BOOKING_INITIALIZED,
    CANCEL_RESERVATION
}